title: Hodl.farm # The title of the blog
author: Test_hodl_local
email: hello@hodl.farm # your email shown in the footer
telegram: t.me/hodl_farm
twitter: "@hodl_farm"
url: https://hodl.farm # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Fertile ground for your cryptos.
favicon: "./favicon.ico" # set the favicon of the site 
show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "assets/img/hodlfarmsheep.png" # avatar in about page
  about_you: Fertile ground for your cryptos.
  email: hello@hodl.farm # your email shown in the footer
 # twitter: "@hodl_farm"
  telegram: t.me/hodl_farm
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  social_links:
# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
